version: '3'
services:
  csgo-stats:
    restart: always
    container_name: csgo-stats
    image: 'satheeshps/csgo-stats'
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./dist/assets:/replays
      - ./dist/db:/app/db
    environment:
      - BASE_PATH=/app
      - DEM_PATH=/replays
      - NODE_ENV=production
    ports:
      - 8080:8080
